'use client';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Building2,Plus,ArrowUpRight,Wallet,Receipt,HardHat} from 'lucide-react';
const money=(v:number)=>new Intl.NumberFormat('es-CR',{style:'currency',currency:'CRC',maximumFractionDigits:0}).format(v);
const defaults=[{id:'loan',name:'Préstamo',amount:587971},{id:'internet',name:'Internet y cable · estimado',amount:53000},{id:'electric',name:'Electricidad · referencia julio',amount:110660},{id:'ev',name:'Compensación EV · estimada',amount:-85000},{id:'gas',name:'Gas de lavado',amount:13000},{id:'municipal',name:'Municipalidad · provisión',amount:20000},{id:'maintenance',name:'Mantenimiento de áreas',amount:30000},{id:'washing',name:'Equipos de lavado · 22 cuotas por confirmar',amount:45000}];
const rentals=[210000,260000,0,230000,240000,0,0,0,260000];
export default function Dashboard(){
const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[month,setMonth]=useState(new Intl.DateTimeFormat('en-CA',{timeZone:'America/Costa_Rica'}).format(new Date()).slice(0,7)),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[kind,setKind]=useState('expense'),[apt,setApt]=useState('general'),[edit,setEdit]=useState<any>(null);
async function refresh(){const r=await fetch('/api/records');const d:any=await r.json();if(!r.ok)throw Error(d.error);setRows(d.records);}
useEffect(()=>{fetch('/api/initialize',{method:'POST'}).then(async r=>{if(!r.ok)throw Error('No se pudieron preparar los registros. Recargá la página para reintentar.');await refresh();}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const c=new AbortController();Promise.resolve(ctx.registerTool({name:'read_apartment_records',description:'Lee los movimientos guardados del proyecto.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{const r=await fetch('/api/records');if(!r.ok)throw Error('No se pudieron cargar los registros');return r.json();}},{signal:c.signal})).catch(()=>{});return()=>c.abort();},[]);
const monthly=rows.filter(r=>r.date?.startsWith(month));const income=monthly.filter(r=>r.kind==='income').reduce((a,r)=>a+r.amount,0);const expenses=monthly.filter(r=>r.kind==='expense'||r.kind==='construction').reduce((a,r)=>a+r.amount,0);
const recurring=defaults.map(d=>({...d,...rows.find(r=>r.id==='rec-'+d.id)}));const projectedCost=recurring.reduce((a,r)=>a+r.amount,0);
function start(k='expense',record:any=null){setKind(k);setApt(record?.apartment||'general');setEdit(record);setOpen(true);}
async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);f.set('kind',kind);f.set('apartment',apt);if(edit?.id)f.set('id',edit.id);try{const r=await fetch('/api/records',{method:'POST',body:f});const d:any=await r.json();if(!r.ok)throw Error(d.error);await refresh();setOpen(false);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
return <div className="app"><header><a className="brand" href="/"><span className="brand-icon"><Building2/></span><span>Santo Tomás<small>PROYECTO APARTAMENTOS</small></span></a><span className="private">Espacio privado</span></header><main><div className="title-row"><div><p className="eyebrow">CONTROL DEL PROYECTO</p><h1>Todo en su lugar.</h1><p className="muted">Alquileres, gastos y avance de tus apartamentos.</p></div><button className="primary" onClick={()=>start()}><Plus size={18}/> Registrar movimiento</button></div><div className="period"><label htmlFor="month">Período</label><input id="month" aria-label="Período" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><span className="muted">Montos en colones costarricenses</span></div>{error&&<div className="error" role="alert">{error} <button onClick={()=>{setLoading(true);refresh().then(()=>setError('')).catch(e=>setError(e.message)).finally(()=>setLoading(false));}}>Reintentar</button></div>}
<div className="stats"><section className="stat featured"><span>Ingreso mensual esperado <ArrowUpRight size={20}/></span><strong>{money(1200000)}</strong><small>5 apartamentos alquilados de 9</small></section><section className="stat"><span>Pagos registrados <Wallet size={20}/></span><strong>{loading?'—':money(income)}</strong><small>Según movimientos del período</small></section><section className="stat"><span>Gastos registrados <Receipt size={20}/></span><strong>{loading?'—':money(expenses)}</strong><small>Incluye construcción del período</small></section><section className="stat"><span>Saldo registrado <HardHat size={20}/></span><strong>{loading?'—':money(income-expenses)}</strong><small>Ingresos menos gastos registrados</small></section></div>
<Tabs defaultValue="rentals"><TabsList className="tablist"><TabsTrigger value="rentals">Apartamentos</TabsTrigger><TabsTrigger value="ledger">Movimientos</TabsTrigger><TabsTrigger value="budget">Gastos mensuales</TabsTrigger><TabsTrigger value="works">Construcción</TabsTrigger></TabsList>
<TabsContent value="rentals"><div className="section-heading"><h2>Los 9 apartamentos</h2><span className="muted">Servicios incluidos en los alquileres</span></div><div className="apartments">{rentals.map((rent,i)=>{const paid=monthly.filter(r=>r.kind==='income'&&r.apartment===String(i+1)).reduce((a,r)=>a+r.amount,0);return <article className={'apartment '+(!rent?'unfinished':'')} key={i}><div className="apt-head"><span className="apt-number">{String(i+1).padStart(2,'0')}</span><span className={'badge '+(!rent?'work':'')}>{rent?'Alquilado':'Por terminar'}</span></div><h3>Apartamento #{i+1}</h3><strong>{rent?money(rent):'En construcción'}{rent>0&&<small> / mes</small>}</strong>{rent>0?<><div className="paid"><span>Registrado: {money(paid)}</span><span>{paid>=rent?'Cubierto':paid>0?'Parcial':'Sin pago registrado'}</span></div><button className="secondary" onClick={()=>start('income',{apartment:String(i+1),amount:Math.max(rent-paid,0),name:'Alquiler apartamento #'+(i+1)})}>Registrar pago</button></>:<p className="muted">Presupuesto y gastos en Construcción.</p>}</article>;})}</div></TabsContent>
<TabsContent value="ledger"><div className="section-heading"><h2>Movimientos del período</h2><button className="secondary" onClick={()=>start()}>Nuevo movimiento</button></div><p className="muted">Los gastos recurrentes son una proyección; registrá cada pago efectivo aquí.</p>{loading?<p>Cargando movimientos…</p>:<div className="ledger">{monthly.filter(r=>!['recurring','budget'].includes(r.kind)).length===0?<p className="empty">No hay movimientos registrados para este período.</p>:monthly.filter(r=>!['recurring','budget'].includes(r.kind)).map(r=><article className="record" key={r.id}><div><strong>{r.name}</strong><p>{r.date} · {r.kind==='income'?'Ingreso':r.kind==='construction'?'Construcción':'Gasto'}{r.apartment!=='general'?' · Apto #'+r.apartment:''}</p>{r.note&&<small>{r.note}</small>}{r.file_name&&<a href={'/api/files?id='+encodeURIComponent(r.id)}>Ver comprobante: {r.file_name}</a>}</div><div className="record-right"><strong className={r.kind==='income'?'positive':''}>{r.kind==='income'?'+':'−'}{money(r.amount)}</strong><button onClick={()=>start(r.kind,r)}>Editar</button></div></article>)}</div>}</TabsContent>
<TabsContent value="budget"><div className="section-heading"><h2>Proyección mensual</h2><span className="muted">Referencias compartidas · septiembre 2026</span></div><div className="budget-layout"><div className="panel">{recurring.map(r=><div className="budget-row" key={r.id}><span>{r.name}</span><strong>{money(r.amount)}</strong><button onClick={()=>start('recurring',{...r,id:r.id.startsWith('rec-')?r.id:'rec-'+r.id})}>Editar</button></div>)}</div><aside className="projection"><p>Saldo mensual estimado</p><strong>{money(1200000-projectedCost)}</strong><p>Ingreso esperado: {money(1200000)}</p><p>Obligaciones netas: {money(projectedCost)}</p><hr/><small>Incluye préstamo y cuota de lavado. La compensación EV reduce la proyección de electricidad. No incluye obras ni gastos no registrados. Confirmá los importes estimados y las cuotas restantes.</small></aside></div></TabsContent>
<TabsContent value="works"><div className="section-heading"><h2>Terminar los próximos espacios</h2><button className="secondary" onClick={()=>start('construction')}>Registrar gasto de obra</button></div><div className="panel"><h3>Presupuesto de referencia</h3>{[{id:'budget-electric',name:'Materiales eléctricos',amount:500000},{id:'budget-structure',name:'Materiales estructurales · tubos de 3 y 4 pulgadas',amount:800000},{id:'budget-labor',name:'Mano de obra estimada',amount:1300000}].map(d=>{const r=rows.find(r=>r.id===d.id)||d;return <div className="budget-row" key={r.id}><span>{r.name}</span><strong>{money(r.amount)}</strong><button onClick={()=>start('budget',r)}>Editar</button></div>;})}<p className="muted">Estimaciones del proyecto completo, sin asignación por apartamento. No se suman a los gastos pagados.</p></div><h3 className="spaced">Gastos de obra registrados</h3><div className="ledger">{rows.filter(r=>r.kind==='construction').map(r=><article className="record" key={r.id}><div><strong>{r.name}</strong><p>{r.date} · {r.apartment==='general'?'General':'Apto #'+r.apartment}</p>{r.file_name&&<a href={'/api/files?id='+r.id}>Ver comprobante</a>}</div><div className="record-right"><strong>{money(r.amount)}</strong><button onClick={()=>start('construction',r)}>Editar</button></div></article>)}</div></TabsContent></Tabs>
<footer>Proyecto Apartamentos · Santo Tomás <span>Los pagos se confirman al registrarlos.</span></footer></main>
<Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{edit?.id?'Editar registro':'Registrar movimiento'}</DialogTitle><DialogDescription>Guardá el monto y, si lo tenés, su comprobante.</DialogDescription></DialogHeader><form onSubmit={save} className="form">{!['recurring','budget'].includes(kind)&&<><label>Tipo<Select value={kind} onValueChange={setKind}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="income">Ingreso de alquiler</SelectItem><SelectItem value="expense">Gasto general</SelectItem><SelectItem value="construction">Gasto de construcción</SelectItem></SelectContent></Select></label><label>Apartamento<Select value={apt} onValueChange={setApt}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="general">General</SelectItem>{rentals.map((_,i)=><SelectItem key={i} value={String(i+1)}>Apartamento #{i+1}</SelectItem>)}</SelectContent></Select></label></>}<label>Descripción<input name="name" required maxLength={200} defaultValue={edit?.name||''}/></label><div className="form-two"><label>Monto en colones<input name="amount" type="number" step="0.01" min={kind==='recurring'?undefined:'0.01'} required defaultValue={edit?.amount||''}/></label><label>Fecha<input name="date" type="date" required defaultValue={edit?.date||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Costa_Rica'}).format(new Date())}/></label></div><label>Notas<textarea name="note" maxLength={1000} defaultValue={edit?.note||''}/></label>{!['recurring','budget'].includes(kind)&&<label>Comprobante (PDF, JPG o PNG; máximo 10 MB)<input name="file" type="file" accept="application/pdf,image/jpeg,image/png"/></label>}{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy||loading}>{busy?'Guardando…':'Guardar registro'}</button></form></DialogContent></Dialog></div>;
}
